src/Entity/Cours.php
<?php

namespace App\Entity;

use App\Repository\CoursRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CoursRepository::class)]
class Cours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_du_cours = null;

    #[ORM\Column(length: 255)]
    private ?string $prix = null;

    #[ORM\Column(length: 255)]
    private ?string $matiere = null;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomDuCours(): ?string
    {
        return $this->nom_du_cours;
    }

    public function setNomDuCours(string $nom_du_cours): static
    {
        $this->nom_du_cours = $nom_du_cours;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getMatiere(): ?string
    {
        return $this->matiere;
    }

    public function setMatiere(string $matiere): static
    {
        $this->matiere = $matiere;

        return $this;
    }

    public function getCategory(): ?category
    {
        return $this->category;
    }

    public function setCategory(?category $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/CoursType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Cours;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CoursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_du_cours')
            ->add('prix')
            ->add('matiere')
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'titre',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cours::class,
        ]);
    }
}

src/Controller/CoursController.php
<?php

namespace App\Controller;

use App\Entity\Cours;
use App\Form\CoursType;
use App\Repository\CoursRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/cours')]
class CoursController extends AbstractController
{
    #[Route('/', name: 'app_cours_index', methods: ['GET'])]
    public function index(CoursRepository $coursRepository): Response
    {
        return $this->render('cours/index.html.twig', [
            'cours' => $coursRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_cours_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $cour = new Cours();
        $form = $this->createForm(CoursType::class, $cour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($cour);
            $entityManager->flush();

            return $this->redirectToRoute('app_cours_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('cours/new.html.twig', [
            'cour' => $cour,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cours_show', methods: ['GET'])]
    public function show(Cours $cour): Response
    {
        return $this->render('cours/show.html.twig', [
            'cour' => $cour,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_cours_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cours $cour, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CoursType::class, $cour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_cours_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('cours/edit.html.twig', [
            'cour' => $cour,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cours_delete', methods: ['POST'])]
    public function delete(Request $request, Cours $cour, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cour->getId(), $request->request->get('_token'))) {
            $entityManager->remove($cour);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_cours_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/cours/_delete_form.html.twig
<form method="post" action="{{ path('app_cours_delete', {'id': cour.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cour.id) }}">
    <button class="btn">Delete</button>
</form>

templates/cours/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/cours/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cours{% endblock %}

{% block body %}
    <h1>Edit Cours</h1>

    {{ include('cours/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_cours_index') }}">back to list</a>

    {{ include('cours/_delete_form.html.twig') }}
{% endblock %}

templates/cours/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cours index{% endblock %}

{% block body %}
    <h1>Cours index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_du_cours</th>
                <th>Prix</th>
                <th>Matiere</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for cour in cours %}
            <tr>
                <td>{{ cour.id }}</td>
                <td>{{ cour.nomDuCours }}</td>
                <td>{{ cour.prix }}</td>
                <td>{{ cour.matiere }}</td>
                <td>
                    <a href="{{ path('app_cours_show', {'id': cour.id}) }}">show</a>
                    <a href="{{ path('app_cours_edit', {'id': cour.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_cours_new') }}">Create new</a>
{% endblock %}

templates/cours/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cours{% endblock %}

{% block body %}
    <h1>Create new Cours</h1>

    {{ include('cours/_form.html.twig') }}

    <a href="{{ path('app_cours_index') }}">back to list</a>
{% endblock %}

templates/cours/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cours{% endblock %}

{% block body %}
    <h1>Cours</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cour.id }}</td>
            </tr>
            <tr>
                <th>Nom_du_cours</th>
                <td>{{ cour.nomDuCours }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ cour.prix }}</td>
            </tr>
            <tr>
                <th>Matiere</th>
                <td>{{ cour.matiere }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_cours_index') }}">back to list</a>

    <a href="{{ path('app_cours_edit', {'id': cour.id}) }}">edit</a>

    {{ include('cours/_delete_form.html.twig') }}
{% endblock %}